apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myapp:latest
          imagePullPolicy: Always
          env:
          - name: HTTP_HOST
            value: "0.0.0.0"
          - name: METRICS_HOST
            value: "0.0.0.0"
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9090
          resources:
            requests:
              memory: 250Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: 200m
          readinessProbe:
            httpGet:
              path: /hello
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /hello
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10