apiVersion: v1
kind: Service
metadata:
  name: myapp-metrics
  namespace: myapp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: myapp
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090