# prom-values.yaml
fullnameOverride: prometheus

alertmanager:
  enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false   # set to true if you also want cluster object metrics

rbac:
  create: true

serviceAccounts:
  server:
    create: true

server:
  retention: 24h
  persistentVolume:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 9090          # expose svc on 9090 (easier to port-forward)
  configmapReload:
    prometheus:
      enabled: true
      # tell the sidecar which URL to POST to
      extraArgs:
        - --reload-url=http://127.0.0.1:8080/-/reload
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 65534

serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      # Self-scrape
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Discover Services annotated with prometheus.io/scrape="true"
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            regex: (https?)
            target_label: __scheme__
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            regex: (.+)
            target_label: __metrics_path__
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            # rewrite target address to the annotated port
            action: replace
            regex: (.+?)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: service
